name: Build MOD APK

on:
  workflow_dispatch:
    inputs:
      package_name:
        default: 'com.jaiho.mod'
      app_name:
        default: 'Jaiho Pro'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
